Pract2602
lenovikov/react-tasks pull request #2
Opened 2021-02-26 19:21 UTC by lenovikov

2021-02-27 19:37 UTC, NearFutureBand requested changes
По коду все отлично, вижу что задачи даются без напряга. Единственное что чуть-чуть не так сделаны 1.1 и 1.2 - там где кнопка и спиннер. Этот момент откомментил, там исправить будет несложно

2021-02-27 19:37 UTC, NearFutureBand commented on src/components/Ex5/index.js
> +            <button onClick={this.change} className={this.state.value? 'loader loader-animated' : '' }>1</button>
Здесь цель задачи была используя тернарный оператор делать выбор между двумя **компонентами**, не классами. С классами уже работали)

2021-02-27 19:37 UTC, NearFutureBand commented on src/components/Ex6/index.js
> +            <button  className={this.props.className? 'loader loader-animated' : '' }>1</button>
Тоже самое здесь, как и в Ex5 - нужно в зависимости от значения пропа выбрать между компонентами - кнопкой либо спиннером. Спиннер кстати с двумя Н пишется))

2021-02-27 19:37 UTC, NearFutureBand commented on src/components/Ex7/index.js
> +            return <li>{item}<Number /></li>
В каждом map нужно не забывать про key проп. Каждый элемент списка (самый внешний компонент) должен иметь проп key и в него нужно передать уникальное для каждого элемента значение. Это рассказывалось на одном из занятий. Здесь можно сам item передать как key.

2021-02-27 19:37 UTC, NearFutureBand commented on src/components/Ex7/index1.js
> +    }
Вот здесь могу подкинуть задачу, как можно вместо этих двух функций сделать одну, которая бы отвечала и за суммирование и за вычитание?

2021-03-02 22:31 UTC, lenovikov commented on src/components/Ex7/index.js
> +            return <li>{item}<Number /></li>
пересмотрел занятие- понял

2021-03-02 22:33 UTC, lenovikov commented on src/components/Ex7/index1.js
> +    }
мне нужно придумать как сделать одну функцию объединив мои?

2021-03-09 12:11 UTC, merged